### ISSUE TITLE
Change Recent Games to Active players on Home Page

### ISSUE THREAD

**Issue by jhonnold** [jhonnold/fndash#30]
This should be a list of currently active players (played a game in the last half hour?)

**Comment by JackSomm** [comment]
Functionality in testing, need to style better

**Comment by jhonnold** [comment]
Could use some QoL adjustments, like when they played. Closing this, it can be reopened if we progress down that road.

**Comment by jhonnold** [comment]
We should clean this up a bit by making these individual user cards that show:
- Name
- Last Game
- Lifetime Kills
- Lifetime KD

**Comment by jhonnold** [comment]
Last game time played - i.e.  (5 minutes ago)
